### PR TITLE
Fixed optional config data tests

### PR DESCRIPTION
**Pull request by DoLearnWhileAlive**
# Pull Request

### Fixed
- Fixed some optional config data tests are never running
- Fixed skipped optional config data tests are not marked accordingly

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscworkshop/142)

### CODE REVIEW

**Review by raandree — COMMENTED** [review]
Good catch, thanks!

What do you think about marking the skipped tests so that people know which tests were actually called?

```powershell
It "Environment of '<Name>' is '<Environment>' and does exist" -TestCases $allNodeTests {
        if ($node.Environment -and $node.Environment -notlike '`[x=*')
        {
            $node.Environment -in $Environments | Should -BeTrue
        }
        else
        {
            Set-ItResult -Skipped -Because "Tests for '$Name' is either not set or like '[x=*'"
        }
    }
```

**Comment by DoLearnWhileAlive** [comment]
That totally makes sense. I've updated the PR accordingly.

**Review by raandree — APPROVED** [review]
:lgtm:

**Comment by raandree** [comment]
Thanks!

**Pull request merged**
